name: Component Missmatch Bug Report
description: Report a bug related to a component missmatch
title: "[Runtime] Entity deserialisation failed on '%s'"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Whoops.. Looks like there is a component missmatch. Please fill in the information below to help us reproduce the issue.
        Makes sure to add `logger.txt` to this issue. NoitaMP usually already opened it for you. If not, you can find it in the Noita installation folder.
  - type: dropdown
    id: os
    attributes:
      label: OS/Operating System
      description: The operating system you are using.
      options:
        - Windows
        - Linux
        - Mac
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: NoitaMP version
      description: The version of NoitaMP you are using. If unsure, just copy the version from the `logger.txt` file.
      placeholder: v4.0.1-alpha+1195
    validations:
      required: true
  - type: textarea
    id: logger
    attributes:
      label: logger.txt content
      description: Paste the content of the `logger.txt` file here.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: If you have any additional information, please add it here.