name: Generate lua doc
run-name: ${{ github.actor }} is generating lua docs 🚀
on: push

jobs:
  generate-lua-docs:
    name: 'Generate lua docs'
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3.3.0

      - name: Print GitHub context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: 'Generate lua docs with lua-language-server'
        shell: cmd
        run: |
          ${{ github.workspace }}\\.building\\lua-language-server-3.6.18-win32-x64\\bin\\lua-language-server.exe --logpath \"${{ github.workspace }}\\docs\\lua-docs\" --configpath \"${{ github.workspace }}\\docs\\lua-docs\\lua-language-server-config.lua\" --doc \"${{ github.workspace }}\\mods\\noita-mp\\files\\scripts\"
          cd ${{ github.workspace }}\\docs\\lua-docs\\ 
          DEL /f *.log

      - name: 'Commit lua docs'
        shell: pwsh
        run: |
          cd ${{ github.workspace }}\\docs\\lua-docs\\
          git config --global user.email \"action@github.com\"
          git config --global user.name \"github-actions\"
          git add .
          git commit -m \"Updated generated lua docs\"
          git push origin
      
      - name: 'Fix wrong paths in lua docs'
        shell: pwsh
        run: |
          cd ${{ github.workspace }}\\docs\\lua-docs\\
          "Set-Alias -Name sed -Value 'C:\\Program Files\\Git\\usr\\bin\\sed.exe'
          $path = echo ${{ github.workspace }} | sed 's#\\#/#g'
          sed -i 's#$path##g' ${{ github.workspace }}\\docs\\lua-docs\\doc.md

          
