name: Generate lua doc
run-name: ${{ github.actor }} is generating lua docs 🚀
on: push
jobs:
  action:
    runs-on: windows-latest

    steps:
      - name: 'Generate lua docs'
      - run: |
          scoop install lua-language-server
          dir "lua-language-server" /s
